"""SQLAlchemy ORM models for SIEM service."""

import uuid
from datetime import datetime
from typing import Any

from sqlalchemy import (
    BigInteger,
    CheckConstraint,
    DateTime,
    ForeignKey,
    Index,
    Integer,
    MetaData,
    Text,
    func,
    text,
)
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, relationship

# Convention из доки Alembic: стабильные имена constraints/индексов,
# чтобы autogenerate мог адресовать их в drop/alter без угадывания.
NAMING_CONVENTION = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    """SQLAlchemy base model."""

    metadata = MetaData(naming_convention=NAMING_CONVENTION)
    type_annotation_map = {dict[str, Any]: JSONB}


class SiemEvent(Base):
    """Security event storage model."""

    __tablename__ = "siem_events"

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True)
    event_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        unique=True,
        comment="UUID for idempotency (at-least-once semantics)",
    )
    event_type: Mapped[str] = mapped_column(
        Text,
        index=True,
        comment="Event type string (e.g., 'auth.login.failed')",
    )
    severity: Mapped[str] = mapped_column(
        Text,
        comment="Severity: info | warning | critical",
    )
    event_timestamp: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        index=True,
        comment="UTC timestamp from producer",
    )
    ingested_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        index=True,
        comment="Consumer-side ingestion timestamp",
    )
    identifiers: Mapped[dict[str, Any]] = mapped_column(
        JSONB,
        server_default=text("'{}'::jsonb"),
        comment="Event identifiers: ip, user_id, request_id, etc.",
    )
    event_metadata: Mapped[dict[str, Any]] = mapped_column(
        JSONB,
        server_default=text("'{}'::jsonb"),
        comment="Event-specific metadata dict (note: column name differs from Pydantic field 'metadata')",
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
    )

    __table_args__ = (
        CheckConstraint(
            "severity IN ('info', 'warning', 'critical')",
            name="severity",
        ),
        Index(
            "ix_siem_events_identifiers_gin",
            "identifiers",
            postgresql_using="gin",
        ),
    )


class CorrelationRule(Base):
    """Correlation rule definition."""

    __tablename__ = "correlation_rules"

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True)
    name: Mapped[str] = mapped_column(
        Text,
        unique=True,
        comment="Rule name (unique)",
    )
    description: Mapped[str | None] = mapped_column(
        Text,
        comment="Rule description",
    )
    rule_type: Mapped[str] = mapped_column(
        Text,
        comment="Rule type: threshold | sequence | aggregate",
    )
    enabled: Mapped[bool] = mapped_column(
        server_default=text("true"),
        index=True,
        comment="Rule enabled status",
    )
    severity: Mapped[str] = mapped_column(
        Text,
        server_default=text("'warning'"),
        comment="Alert severity for this rule",
    )
    config: Mapped[dict[str, Any]] = mapped_column(
        JSONB,
        server_default=text("'{}'::jsonb"),
        comment="Rule configuration (per rule_type)",
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
    )

    # Relationships
    alerts: Mapped[list["SiemAlert"]] = relationship(
        back_populates="rule",
        cascade="all, delete-orphan",
    )

    __table_args__ = (
        CheckConstraint(
            "rule_type IN ('threshold', 'sequence', 'aggregate')",
            name="rule_type",
        ),
        CheckConstraint(
            "severity IN ('info', 'warning', 'critical')",
            name="severity",
        ),
    )


class SiemAlert(Base):
    """Alert generated by correlation engine."""

    __tablename__ = "siem_alerts"

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True)
    rule_id: Mapped[int] = mapped_column(
        BigInteger,
        ForeignKey("correlation_rules.id", ondelete="RESTRICT"),
        index=True,
        comment="FK to correlation_rules",
    )
    severity: Mapped[str] = mapped_column(
        Text,
        comment="Alert severity (info | warning | critical)",
    )
    status: Mapped[str] = mapped_column(
        Text,
        server_default=text("'new'"),
        index=True,
        comment="Alert status: new | acknowledged | resolved | expired",
    )
    group_key: Mapped[str | None] = mapped_column(
        Text,
        comment="Grouping key (ip, user_id, etc.) or NULL for no grouping",
    )
    matched_events_count: Mapped[int] = mapped_column(
        Integer,
        server_default=text("1"),
        comment="Number of correlation firings folded into this alert",
    )
    first_event_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("siem_events.event_id", ondelete="RESTRICT"),
        comment="FK to siem_events (first matched event)",
    )
    latest_event_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("siem_events.event_id", ondelete="RESTRICT"),
        comment="FK to siem_events (latest matched event)",
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        index=True,
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
    )
    acknowledged_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True),
        comment="Timestamp when alert was acknowledged",
    )
    acknowledged_by: Mapped[str | None] = mapped_column(
        Text,
        comment="User ID who acknowledged the alert",
    )
    resolved_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True),
        comment="Timestamp when alert was resolved",
    )
    resolved_by: Mapped[str | None] = mapped_column(
        Text,
        comment="User ID who resolved the alert",
    )

    # Relationships
    rule: Mapped[CorrelationRule] = relationship(back_populates="alerts")

    __table_args__ = (
        CheckConstraint(
            "severity IN ('info', 'warning', 'critical')",
            name="severity",
        ),
        CheckConstraint(
            "status IN ('new', 'acknowledged', 'resolved', 'expired')",
            name="status",
        ),
        # Инвариант open-alert политики: не больше одного открытого алерта на
        # (rule_id, group_key); NULLS NOT DISTINCT — NULL-группа тоже единственна.
        # Опора атомарного upsert'а в AlertDeduper (ON CONFLICT).
        Index(
            "uq_siem_alerts_open_alert",
            "rule_id",
            "group_key",
            unique=True,
            postgresql_where=text("status = 'new'"),
            postgresql_nulls_not_distinct=True,
        ),
    )
