"""SQLAlchemy ORM models for SIEM service."""

from typing import Any

from sqlalchemy import (
    TIMESTAMP,
    BigInteger,
    Boolean,
    Column,
    ForeignKey,
    Index,
    Integer,
    String,
    Text,
)
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import DeclarativeBase, relationship


class Base(DeclarativeBase):
    """SQLAlchemy base model."""

    type_annotation_map = {dict[str, Any]: JSONB}


class SiemEvent(Base):
    """Security event storage model."""

    __tablename__ = "siem_events"

    id = Column(BigInteger, primary_key=True, autoincrement=True)
    event_id = Column(
        UUID(as_uuid=True),
        nullable=False,
        unique=True,
        comment="UUID for idempotency (at-least-once semantics)",
    )
    event_type = Column(
        String(255),
        nullable=False,
        comment="Event type string (e.g., 'auth.login.failed')",
    )
    severity = Column(
        String(20),
        nullable=False,
        comment="Severity: info | warning | critical",
    )
    event_timestamp = Column(
        TIMESTAMP(timezone=True),
        nullable=False,
        comment="UTC timestamp from producer",
    )
    ingested_at = Column(
        TIMESTAMP(timezone=True),
        nullable=False,
        server_default="now()",
        comment="Consumer-side ingestion timestamp",
    )
    identifiers = Column(
        JSONB,
        nullable=False,
        server_default="'{}'::jsonb",
        comment="Event identifiers: ip, user_id, request_id, etc.",
    )
    event_metadata = Column(
        JSONB,
        nullable=False,
        server_default="'{}'::jsonb",
        comment="Event-specific metadata dict (note: column name differs from Pydantic field 'metadata')",
    )
    created_at = Column(
        TIMESTAMP(timezone=True),
        nullable=False,
        server_default="now()",
    )

    __table_args__ = (
        Index("idx_siem_events_event_type", "event_type"),
        Index("idx_siem_events_severity", "severity"),
        Index("idx_siem_events_ingested_at", "ingested_at"),
        Index("idx_siem_events_event_timestamp", "event_timestamp"),
        Index("idx_siem_events_identifiers_gin", "identifiers", postgresql_using="gin"),
    )


class CorrelationRule(Base):
    """Correlation rule definition."""

    __tablename__ = "correlation_rules"

    id = Column(BigInteger, primary_key=True, autoincrement=True)
    name = Column(
        String(255),
        nullable=False,
        unique=True,
        comment="Rule name (unique)",
    )
    description = Column(
        Text,
        nullable=True,
        comment="Rule description",
    )
    rule_type = Column(
        String(50),
        nullable=False,
        comment="Rule type: threshold | sequence | aggregate",
    )
    enabled = Column(
        Boolean,
        nullable=False,
        server_default="true",
        comment="Rule enabled status",
    )
    severity = Column(
        String(20),
        nullable=False,
        server_default="'warning'",
        comment="Alert severity for this rule",
    )
    config = Column(
        JSONB,
        nullable=False,
        server_default="'{}'::jsonb",
        comment="Rule configuration (per rule_type)",
    )
    created_at = Column(
        TIMESTAMP(timezone=True),
        nullable=False,
        server_default="now()",
    )
    updated_at = Column(
        TIMESTAMP(timezone=True),
        nullable=False,
        server_default="now()",
    )

    # Relationships
    alerts = relationship(
        "SiemAlert",
        back_populates="rule",
        cascade="all, delete-orphan",
    )

    __table_args__ = (Index("idx_correlation_rules_enabled", "enabled"),)


class SiemAlert(Base):
    """Alert generated by correlation engine."""

    __tablename__ = "siem_alerts"

    id = Column(BigInteger, primary_key=True, autoincrement=True)
    rule_id = Column(
        BigInteger,
        ForeignKey("correlation_rules.id", ondelete="RESTRICT"),
        nullable=False,
        comment="FK to correlation_rules",
    )
    severity = Column(
        String(20),
        nullable=False,
        comment="Alert severity (info | warning | critical)",
    )
    status = Column(
        String(20),
        nullable=False,
        server_default="'new'",
        comment="Alert status: new | acknowledged | resolved",
    )
    group_key = Column(
        String(255),
        nullable=True,
        comment="Grouping key (ip, user_id, etc.) or NULL for no grouping",
    )
    matched_events_count = Column(
        Integer,
        nullable=False,
        server_default="1",
        comment="Number of events matched for this alert",
    )
    first_event_id = Column(
        UUID(as_uuid=True),
        ForeignKey("siem_events.event_id", ondelete="RESTRICT"),
        nullable=False,
        comment="FK to siem_events (first matched event)",
    )
    latest_event_id = Column(
        UUID(as_uuid=True),
        ForeignKey("siem_events.event_id", ondelete="RESTRICT"),
        nullable=False,
        comment="FK to siem_events (latest matched event)",
    )
    created_at = Column(
        TIMESTAMP(timezone=True),
        nullable=False,
        server_default="now()",
    )
    updated_at = Column(
        TIMESTAMP(timezone=True),
        nullable=False,
        server_default="now()",
    )
    acknowledged_at = Column(
        TIMESTAMP(timezone=True),
        nullable=True,
        comment="Timestamp when alert was acknowledged",
    )
    acknowledged_by = Column(
        String(255),
        nullable=True,
        comment="User ID who acknowledged the alert",
    )
    resolved_at = Column(
        TIMESTAMP(timezone=True),
        nullable=True,
        comment="Timestamp when alert was resolved",
    )
    resolved_by = Column(
        String(255),
        nullable=True,
        comment="User ID who resolved the alert",
    )

    # Relationships
    rule = relationship(
        "CorrelationRule",
        back_populates="alerts",
    )

    __table_args__ = (
        Index("idx_siem_alerts_rule_id", "rule_id"),
        Index("idx_siem_alerts_status", "status"),
        Index("idx_siem_alerts_created_at", "created_at"),
        Index(
            "idx_siem_alerts_open_alert_lookup",
            "rule_id",
            "group_key",
            "status",
            postgresql_where="status = 'new'",
        ),
    )
