"""db slice: text types, open-alert unique index, drop severity index

Revision ID: d944c66cc700
Revises: 0917133ea9b5
Create Date: 2026-06-12 21:52:16.342801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd944c66cc700'
down_revision: Union[str, Sequence[str], None] = '0917133ea9b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('correlation_rules', 'name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_comment='Rule name (unique)',
               existing_nullable=False)
    op.alter_column('correlation_rules', 'rule_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Text(),
               existing_comment='Rule type: threshold | sequence | aggregate',
               existing_nullable=False)
    op.alter_column('correlation_rules', 'severity',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Text(),
               existing_comment='Alert severity for this rule',
               existing_nullable=False,
               existing_server_default=sa.text("'warning'::character varying"))
    op.alter_column('siem_alerts', 'severity',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Text(),
               existing_comment='Alert severity (info | warning | critical)',
               existing_nullable=False)
    op.alter_column('siem_alerts', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Text(),
               comment='Alert status: new | acknowledged | resolved | expired',
               existing_comment='Alert status: new | acknowledged | resolved',
               existing_nullable=False,
               existing_server_default=sa.text("'new'::character varying"))
    op.alter_column('siem_alerts', 'group_key',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_comment='Grouping key (ip, user_id, etc.) or NULL for no grouping',
               existing_nullable=True)
    op.alter_column('siem_alerts', 'matched_events_count',
               existing_type=sa.INTEGER(),
               comment='Number of correlation firings folded into this alert',
               existing_comment='Number of events matched for this alert',
               existing_nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('siem_alerts', 'acknowledged_by',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_comment='User ID who acknowledged the alert',
               existing_nullable=True)
    op.alter_column('siem_alerts', 'resolved_by',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_comment='User ID who resolved the alert',
               existing_nullable=True)
    op.drop_index(op.f('idx_siem_alerts_open_alert_lookup'), table_name='siem_alerts', postgresql_where="((status)::text = 'new'::text)")
    op.create_index('uq_siem_alerts_open_alert', 'siem_alerts', ['rule_id', 'group_key'], unique=True, postgresql_where=sa.text("status = 'new'"), postgresql_nulls_not_distinct=True)
    op.alter_column('siem_events', 'event_type',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_comment="Event type string (e.g., 'auth.login.failed')",
               existing_nullable=False)
    op.alter_column('siem_events', 'severity',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Text(),
               existing_comment='Severity: info | warning | critical',
               existing_nullable=False)
    op.alter_column('siem_events', 'event_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment="Event-specific metadata dict (note: column name differs from Pydantic field 'metadata')",
               existing_comment='Event-specific metadata dict',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_index(op.f('idx_siem_events_severity'), table_name='siem_events')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_siem_events_severity'), 'siem_events', ['severity'], unique=False)
    op.alter_column('siem_events', 'event_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Event-specific metadata dict',
               existing_comment="Event-specific metadata dict (note: column name differs from Pydantic field 'metadata')",
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('siem_events', 'severity',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=20),
               existing_comment='Severity: info | warning | critical',
               existing_nullable=False)
    op.alter_column('siem_events', 'event_type',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_comment="Event type string (e.g., 'auth.login.failed')",
               existing_nullable=False)
    op.drop_index('uq_siem_alerts_open_alert', table_name='siem_alerts', postgresql_where=sa.text("status = 'new'"), postgresql_nulls_not_distinct=True)
    op.create_index(op.f('idx_siem_alerts_open_alert_lookup'), 'siem_alerts', ['rule_id', 'group_key', 'status'], unique=False, postgresql_where="((status)::text = 'new'::text)")
    op.alter_column('siem_alerts', 'resolved_by',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_comment='User ID who resolved the alert',
               existing_nullable=True)
    op.alter_column('siem_alerts', 'acknowledged_by',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_comment='User ID who acknowledged the alert',
               existing_nullable=True)
    op.alter_column('siem_alerts', 'matched_events_count',
               existing_type=sa.INTEGER(),
               comment='Number of events matched for this alert',
               existing_comment='Number of correlation firings folded into this alert',
               existing_nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('siem_alerts', 'group_key',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_comment='Grouping key (ip, user_id, etc.) or NULL for no grouping',
               existing_nullable=True)
    op.alter_column('siem_alerts', 'status',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=20),
               comment='Alert status: new | acknowledged | resolved',
               existing_comment='Alert status: new | acknowledged | resolved | expired',
               existing_nullable=False,
               existing_server_default=sa.text("'new'::character varying"))
    op.alter_column('siem_alerts', 'severity',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=20),
               existing_comment='Alert severity (info | warning | critical)',
               existing_nullable=False)
    op.alter_column('correlation_rules', 'severity',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=20),
               existing_comment='Alert severity for this rule',
               existing_nullable=False,
               existing_server_default=sa.text("'warning'::character varying"))
    op.alter_column('correlation_rules', 'rule_type',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=50),
               existing_comment='Rule type: threshold | sequence | aggregate',
               existing_nullable=False)
    op.alter_column('correlation_rules', 'name',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_comment='Rule name (unique)',
               existing_nullable=False)
    # ### end Alembic commands ###
