"""add artifact_blobs table

Revision ID: 05b404b12f90
Revises: 13f18167a945
Create Date: 2026-07-15 23:46:03.155120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05b404b12f90'
down_revision: Union[str, Sequence[str], None] = '13f18167a945'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artifact_blobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('artifact_id', sa.UUID(), nullable=False),
    sa.Column('mime_type', sa.Text(), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=False),
    sa.ForeignKeyConstraint(['artifact_id'], ['artifacts.id'], name=op.f('fk_artifact_blobs_artifact_id_artifacts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_artifact_blobs'))
    )
    op.create_index(op.f('ix_artifact_blobs_artifact_id'), 'artifact_blobs', ['artifact_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_artifact_blobs_artifact_id'), table_name='artifact_blobs')
    op.drop_table('artifact_blobs')
    # ### end Alembic commands ###
