"""add api_key_hint and mcp_server_disables

Revision ID: 2902408bdfd5
Revises: 4c786a9bcae6
Create Date: 2026-04-05 17:06:24.324788

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2902408bdfd5"
down_revision: Union[str, Sequence[str], None] = "4c786a9bcae6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "mcp_server_disables",
        sa.Column("scope_type", sa.String(length=10), nullable=False),
        sa.Column("scope_id", sa.UUID(), nullable=False),
        sa.Column("server_id", sa.UUID(), nullable=False),
        sa.CheckConstraint("scope_type IN ('project', 'thread')", name="ck_scope_type"),
        sa.PrimaryKeyConstraint("scope_type", "scope_id", "server_id"),
    )
    op.add_column(
        "project_mcp_servers",
        sa.Column("api_key_hint", sa.String(length=20), nullable=True),
    )
    op.add_column(
        "thread_mcp_servers",
        sa.Column("api_key_hint", sa.String(length=20), nullable=True),
    )
    op.add_column(
        "user_mcp_servers",
        sa.Column("api_key_hint", sa.String(length=20), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_mcp_servers", "api_key_hint")
    op.drop_column("thread_mcp_servers", "api_key_hint")
    op.drop_column("project_mcp_servers", "api_key_hint")
    op.drop_table("mcp_server_disables")
    # ### end Alembic commands ###
