model_config:
  name: "gpt-4.1-mini"
  temperature: 0.1
  max_tokens: 4000

graph_config:
  nodes:
    - name: "generating_content"
      type: "content_generator"
    - name: "generating_questions" 
      type: "question_generator"
    - name: "answer_question"
      type: "answer_generator"
  
  edges:
    - from: "START"
      to: "generating_content"
    - from: "generating_content"
      to: "generating_questions"
    - from: "generating_questions"
      to: "answer_question"
    - from: "answer_question"
      to: "END"

output_config:
  save_format: "markdown"
  output_directory: "./data/outputs" 