"""Test-database harness: testcontainers Postgres + alembic + transactional rollback.

Shared building blocks used by each package's conftest. The flow per the testing
conventions:

* a session-scoped Postgres container (cheap, immutable) — one container per
  worker under ``pytest -n`` (each xdist worker is its own session), a single
  container serially;
* schema via ``alembic upgrade head`` (same path as prod, catches migration drift);
* a per-worker database name under ``pytest -n`` (``PYTEST_XDIST_WORKER``) — under
  xdist that DB lives on the worker's own container, so workers never collide;
* per-test isolation via an outer transaction + savepoint, rolled back in teardown.
"""

from __future__ import annotations

import os
from collections.abc import AsyncIterator
from contextlib import asynccontextmanager
from dataclasses import dataclass
from pathlib import Path

from alembic import command
from alembic.config import Config
from alembic.util.exc import AutogenerateDiffsDetected
from sqlalchemy import text
from sqlalchemy.engine.url import make_url
from sqlalchemy.ext.asyncio import (
    AsyncConnection,
    AsyncEngine,
    AsyncSession,
    create_async_engine,
)


def worker_id() -> str:
    """xdist worker id (``gw0``...), or ``main`` for a non-parallel run."""
    return os.environ.get("PYTEST_XDIST_WORKER", "main")


def worker_db_name(base: str) -> str:
    """Per-worker database name so parallel workers never share data."""
    return f"{base}_{worker_id()}"


@dataclass(frozen=True)
class DbUrls:
    """A driver-qualified URL plus the admin URL used to create the DB."""

    db_url: str
    admin_url: str


def make_urls(container_url: str, db_name: str, driver: str) -> DbUrls:
    """Rewrite a testcontainer URL onto ``db_name`` with the project's driver.

    ``container_url`` comes from ``PostgresContainer.get_connection_url()``
    (``postgresql+psycopg2://user:pass@host:port/test``). We swap the driver
    (backend → ``psycopg``, siem → ``asyncpg``) and the database name; the admin
    URL keeps the container's default db for ``CREATE DATABASE``.
    """
    url = make_url(container_url).set(drivername=f"postgresql+{driver}")
    return DbUrls(
        db_url=url.set(database=db_name).render_as_string(hide_password=False),
        admin_url=url.render_as_string(hide_password=False),
    )


def _alembic_config(alembic_ini: str) -> Config:
    """Build an Alembic ``Config`` whose ``script_location`` is cwd-independent.

    Some alembic.ini files use a relative ``script_location`` (siem-service),
    which alembic resolves against the current working directory. We run from the
    repo root, so anchor a relative location to the ini's directory instead.
    """
    cfg = Config(alembic_ini)
    script_location = cfg.get_main_option("script_location")
    if script_location and not os.path.isabs(script_location):
        anchored = Path(alembic_ini).resolve().parent / script_location
        cfg.set_main_option("script_location", str(anchored))
    return cfg


async def create_database(admin_url: str, db_name: str) -> None:
    """Create ``db_name`` if absent (idempotent across worker restarts)."""
    engine = create_async_engine(admin_url, isolation_level="AUTOCOMMIT")
    try:
        async with engine.connect() as conn:
            exists = await conn.scalar(
                text("SELECT 1 FROM pg_database WHERE datname = :n"),
                {"n": db_name},
            )
            if not exists:
                await conn.execute(text(f'CREATE DATABASE "{db_name}"'))
    finally:
        await engine.dispose()


def run_migrations(alembic_ini: str, db_url: str, env: dict[str, str]) -> None:
    """Run ``alembic upgrade head`` against ``db_url``.

    Both alembic env.py files read the URL from their ``Settings()`` (env vars),
    so we set those vars before invoking. ``env`` carries the per-service env-var
    name → value (e.g. ``DATABASE_URL`` / ``SIEM_DATABASE_URL`` plus the required
    ``*_JWT_SECRET``). The drift guard reuses the same wiring.
    """
    previous = {k: os.environ.get(k) for k in env}
    os.environ.update(env)
    try:
        cfg = _alembic_config(alembic_ini)
        command.upgrade(cfg, "head")
    finally:
        for key, value in previous.items():
            if value is None:
                os.environ.pop(key, None)
            else:
                os.environ[key] = value


def check_migration_drift(alembic_ini: str, db_url: str, env: dict[str, str]) -> None:
    """Assert ``alembic check`` finds no model↔migration drift.

    Runs ``alembic check`` (autogenerate dry-run) against a DB already at head.
    Raises ``AssertionError`` if the models have changes not captured by a
    migration — the drift guard for one alembic chain. Run per chain separately.
    """
    previous = {k: os.environ.get(k) for k in env}
    os.environ.update(env)
    try:
        cfg = _alembic_config(alembic_ini)
        try:
            command.check(cfg)
        except AutogenerateDiffsDetected as exc:
            raise AssertionError(
                f"Model↔migration drift detected (run `alembic revision "
                f"--autogenerate`): {exc}"
            ) from exc
    finally:
        for key, value in previous.items():
            if value is None:
                os.environ.pop(key, None)
            else:
                os.environ[key] = value


@asynccontextmanager
async def transactional_session(
    engine: AsyncEngine,
) -> AsyncIterator[AsyncSession]:
    """Yield a session bound to an outer transaction, rolled back on exit.

    Outer transaction on the connection + a ``Session`` joined with
    ``join_transaction_mode="create_savepoint"``: code under test may call
    ``session.commit()`` freely — everything lives inside the savepoint and is
    discarded when the outer transaction rolls back. Function-scoped (mutable).
    """
    conn: AsyncConnection = await engine.connect()
    trans = await conn.begin()
    session = AsyncSession(
        bind=conn,
        expire_on_commit=False,
        join_transaction_mode="create_savepoint",
    )
    try:
        yield session
    finally:
        await session.close()
        await trans.rollback()
        await conn.close()
